# Build settings
include: [
  _pages
]
exclude: [
  README.md,
  firebase.json,
  Gemfile,
  Gemfile.lock,
  node_modules,
  package.json,
  postcss.config.js,
  webpack.config.js,
  webpack.config.babel.js,
  yarn.lock
]
permalink: /:title/
collections:
  case_studies:
    output: true
